### ISSUE TITLE
Why the dependency on Android support?

### ISSUE THREAD

**Issue by sanity** [scana/ok-gradle#13]
This isn't a big issue, but I'm curious why the plugin depends on Android support being enabled in IntelliJ - seems like it should work with any Gradle project, android or not.

**Comment by scana** [comment]
Hi, the plugin is using some classes from Android Support plugin (e.g. for managing adding dependencies to gradle files).

This could be enhanced by extracting specific classes from Android Support plugin and embedding them into this one.

**Comment by scana** [comment]
Tracked here: https://github.com/scana/ok-gradle/pull/22

**Comment by scana** [comment]
@sanity I have finally found some spare time to remove dependency on Android Support plugin - available in `1.0.0` 😄

**Comment by sanity** [comment]
> @sanity I have finally found some spare time to remove dependency on Android Support plugin - available in `1.0.0` 😄 

Thank you :)
