### ISSUE TITLE
Compatibility with build.gradle.kts

### ISSUE THREAD

**Issue by jmfayard** [scana/ok-gradle#15]
Hello @scana !

I want to try your plugin next week, it seems super useful. 

One thing is that half of my Gradle is in Groovy (`build.gradle`) while the other half is in Kotlin (`build.gradle.kts`). 

As you can see here, it's almost the same except for the parenthesis and double quotes (like in java) instead of single quotes)

https://github.com/jmfayard/gradle-kotlin-dsl-libs/blob/50dace493f87711e1fead346160a9dcf12d3cd43/build.gradle.kts#L40-L49

```diff
-implementation 'com.square.retrofit:retrofit2:2.3.0'
+implementation("com.square.retrofit:retrofit2:2.3.0")
```

Actually the latter syntax is totally valid in a `build.gradle` too!

I could try to submit a pull request if you are interested

**Comment by scana** [comment]
Hey @jmfayard, thanks for pointing this out.
I think it should be quite easy to verify whether it's a kotlin-based gradle file or a groovy one. Based on this, we could choose which format should be used.

I'll take a look into this.

**Comment by jmfayard** [comment]
> I think it should be quite easy to verify whether it's a kotlin-based gradle file or a groovy one. 

Yes, it's either called `build.gradle` or `build.gradle.kts` :D

**Comment by scana** [comment]
Hey @jmfayard so, after almost a year and a half, `build.gradle.kts` files are finally supported in version`0.5.0`. 
Should be available soon :)

**Comment by jmfayard** [comment]
Nice @scana  💯
