### ISSUE TITLE
Can not show module names after run this demo.

### ISSUE THREAD

**Issue by Harsh2402** [scana/ok-gradle#17]
I have cloned this project and run it.
And in Android studio, I can not show the module names.

**Comment by scana** [comment]
Hey @Harsh2402 thanks for trying out my plugin!
Unfortunately, I know nothing about your project's structure and it might be crucial when detecting different modules. Would you care to share some more details or maybe a sample project?

**Comment by Harsh2402** [comment]
@scana 
I have just cloned this project in `IntelliJ IDEA CE` and run it in Android Studio.
And checked, but can not show the module.

**Comment by scana** [comment]
@Harsh2402 still, I have no way of debugging this until you provide me with a sample project that you try to open in Android Studio.
Please, feel free to reopen this issue if you'll have more info.

**Comment by scana** [comment]
@Harsh2402 I think I might have resolved your issue with `1.0.0` - it is currently waiting for Jetbrains's approval, but you can skip the wait and grab it from Releases page.
