### ISSUE TITLE
Can you support AndroidX？

### ISSUE THREAD

**Issue by zongxiaomi** [scana/ok-gradle#23]
I want to use AndroidX ，but the result of searched is null

**Comment by scana** [comment]
Hi @zongxiaomi,  which artifact are you looking for?
I added support for AndroidX packages in version [0.4.0](https://github.com/scana/ok-gradle/releases/tag/v0.4.0).

![Screenshot 2020-03-24 at 13 59 30](https://user-images.githubusercontent.com/1139325/77428041-bf1d8300-6dd7-11ea-9fe3-94ea6b7e3809.png)

**Comment by zongxiaomi** [comment]
o sorry ,my old version,thank you
